//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RabbitMQWrapper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RabbitMQWrapper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The RabbitMQ channel closed unexpectedly: {0}.
        /// </summary>
        internal static string ChannelClosedLogEntry {
            get {
                return ResourceManager.GetString("ChannelClosedLogEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RabbitMQ Client Certificate was not found in location &apos;{0}&apos;..
        /// </summary>
        internal static string ClientCertificateNotFoundError {
            get {
                return ResourceManager.GetString("ClientCertificateNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Section &apos;{0}&apos; was not found..
        /// </summary>
        internal static string ConfigurationSectionNotFoundError {
            get {
                return ResourceManager.GetString("ConfigurationSectionNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelling Connection....
        /// </summary>
        internal static string ConnectionCancelledLogEntry {
            get {
                return ResourceManager.GetString("ConnectionCancelledLogEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect to RabbitMQ. Retrying in {0}ms. {1}.
        /// </summary>
        internal static string ConnectionFailedLogEntry {
            get {
                return ResourceManager.GetString("ConnectionFailedLogEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Lost..
        /// </summary>
        internal static string ConnectionLostLogEntry {
            get {
                return ResourceManager.GetString("ConnectionLostLogEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Restored..
        /// </summary>
        internal static string ConnectionRestoredLogEntry {
            get {
                return ResourceManager.GetString("ConnectionRestoredLogEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find consumer with name &apos;{0}&apos; in application configuration file..
        /// </summary>
        internal static string ConsumerNameNotFoundError {
            get {
                return ResourceManager.GetString("ConsumerNameNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The RabbitMQ connection was closed while attempting to consume messages..
        /// </summary>
        internal static string ConsumingConnectionClosedLogEntry {
            get {
                return ResourceManager.GetString("ConsumingConnectionClosedLogEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started consuming from queue &apos;{0}&apos; with RabbitMQ consumer tag &apos;{1}&apos;..
        /// </summary>
        internal static string ConsumptionStartedLogEntry {
            get {
                return ResourceManager.GetString("ConsumptionStartedLogEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find unique certificate with subject name &apos;{0}&apos;. (Found {1} certificates)..
        /// </summary>
        internal static string CouldNotFindCertificateError {
            get {
                return ResourceManager.GetString("CouldNotFindCertificateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to create connection..
        /// </summary>
        internal static string CreatingConnectionLogEntry {
            get {
                return ResourceManager.GetString("CreatingConnectionLogEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating new channel/model..
        /// </summary>
        internal static string CreatingModelLogEntry {
            get {
                return ResourceManager.GetString("CreatingModelLogEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A fatal error occurred. Shutting down..
        /// </summary>
        internal static string FatalErrorLogEntry {
            get {
                return ResourceManager.GetString("FatalErrorLogEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acknowledged message with delivery tag &apos;{0}&apos; from queue &apos;{1}&apos;..
        /// </summary>
        internal static string MessageAcknowledgedLogEntry {
            get {
                return ResourceManager.GetString("MessageAcknowledgedLogEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dequeued message with delivery tag &apos;{0}&apos; from queue &apos;{1}&apos;..
        /// </summary>
        internal static string MessageDequeuedLogEntry {
            get {
                return ResourceManager.GetString("MessageDequeuedLogEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid message received with delivery tag &apos;{0}&apos; from queue &apos;{1}&apos;. Validation errors: {2}..
        /// </summary>
        internal static string MessageFailsValidationLogEntry {
            get {
                return ResourceManager.GetString("MessageFailsValidationLogEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negatively acknowledged message with delivery tag &apos;{0}&apos; from queue &apos;{1}&apos;..
        /// </summary>
        internal static string MessageNegativelyAcknowledgedLogEntry {
            get {
                return ResourceManager.GetString("MessageNegativelyAcknowledgedLogEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message with delivery tag &apos;{0}&apos; has been successfully processed..
        /// </summary>
        internal static string MessageProcessedLogEntry {
            get {
                return ResourceManager.GetString("MessageProcessedLogEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A message with delivery tag &apos;{0}&apos; has been received. Processing....
        /// </summary>
        internal static string MessageReceivedLogEntry {
            get {
                return ResourceManager.GetString("MessageReceivedLogEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negatively acknowledged and requeued message with delivery tag &apos;{0}&apos; from queue &apos;{1}&apos;..
        /// </summary>
        internal static string MessageRequeuedLogEntry {
            get {
                return ResourceManager.GetString("MessageRequeuedLogEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A message sent to exchange &apos;{0}&apos; with routing key &apos;{1}&apos; was returned: {2}.
        /// </summary>
        internal static string MessageReturnedLogEntry {
            get {
                return ResourceManager.GetString("MessageReturnedLogEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully deserialized and validated message with delivery tag &apos;{0}&apos; from queue &apos;{1}&apos;..
        /// </summary>
        internal static string MessageSuccessfullyReceivedLogEntry {
            get {
                return ResourceManager.GetString("MessageSuccessfullyReceivedLogEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received negative publisher confirm for delivery tag &apos;{0}&apos;; multiple = {1}. Resending messages....
        /// </summary>
        internal static string NegativePublisherConfirmReceivedLogEntry {
            get {
                return ResourceManager.GetString("NegativePublisherConfirmReceivedLogEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message with delivery tag &apos;{0}&apos; failed to be processed. {1}.
        /// </summary>
        internal static string ProcessingErrorLogEntry {
            get {
                return ResourceManager.GetString("ProcessingErrorLogEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received publisher confirm for delivery tag &apos;{0}&apos;; multiple = {1}..
        /// </summary>
        internal static string PublisherConfirmReceivedLogEntry {
            get {
                return ResourceManager.GetString("PublisherConfirmReceivedLogEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find publisher with name &apos;{0}&apos; in application configuration file..
        /// </summary>
        internal static string PublisherNameNotFoundError {
            get {
                return ResourceManager.GetString("PublisherNameNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The RabbitMQ connection was closed while attempting to publish messages..
        /// </summary>
        internal static string PublishingConnectionClosedLogEntry {
            get {
                return ResourceManager.GetString("PublishingConnectionClosedLogEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publishing message to exchange &apos;{0}&apos; with routing key &apos;{1}&apos;: {2}.
        /// </summary>
        internal static string PublishingMessageLogEntry {
            get {
                return ResourceManager.GetString("PublishingMessageLogEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish message with delivery tag &apos;{0}&apos; has timed out. Resending....
        /// </summary>
        internal static string PublishMessageTimeoutLogEntry {
            get {
                return ResourceManager.GetString("PublishMessageTimeoutLogEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred when trying to create a temporary queue..
        /// </summary>
        internal static string TemporaryQueueCreationError {
            get {
                return ResourceManager.GetString("TemporaryQueueCreationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating message of type &apos;{0}&apos;..
        /// </summary>
        internal static string ValidatingMessageLogEntry {
            get {
                return ResourceManager.GetString("ValidatingMessageLogEntry", resourceCulture);
            }
        }
    }
}
